FROM node:20-bullseye AS base
RUN apt-get update && apt-get install -y --no-install-recommends ffmpeg && rm -rf /var/lib/apt/lists/*

FROM base AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Build-time env args to bake into the image
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG SUPABASE_SERVICE_ROLE_KEY
ARG OPENAI_API_KEY
ARG ANTHROPIC_API_KEY
ARG ELEVENLABS_API_KEY
ARG FAL_API_KEY
ARG SPEECHIFY_API_KEY
ARG MURF_API_KEY
ARG MINIMAX_KEY
ARG STORYBLOCKS_API_KEY
ARG SHOTSTACK_API_KEY
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG NEXTAUTH_URL
ARG NEXTAUTH_SECRET
ARG GOOGLE_DRIVE_CLIENT_ID
ARG GOOGLE_DRIVE_CLIENT_SECRET
ARG GOOGLE_DRIVE_REDIRECT_URI
ARG GOOGLE_DRIVE_REFRESH_TOKEN

ENV NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL} \
    NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY} \
    SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY} \
    OPENAI_API_KEY=${OPENAI_API_KEY} \
    ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY} \
    ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY} \
    FAL_API_KEY=${FAL_API_KEY} \
    SPEECHIFY_API_KEY=${SPEECHIFY_API_KEY} \
    MURF_API_KEY=${MURF_API_KEY} \
    MINIMAX_KEY=${MINIMAX_KEY} \
    STORYBLOCKS_API_KEY=${STORYBLOCKS_API_KEY} \
    SHOTSTACK_API_KEY=${SHOTSTACK_API_KEY} \
    GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID} \
    GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET} \
    NEXTAUTH_URL=${NEXTAUTH_URL} \
    NEXTAUTH_SECRET=${NEXTAUTH_SECRET} \
    GOOGLE_DRIVE_CLIENT_ID=${GOOGLE_DRIVE_CLIENT_ID} \
    GOOGLE_DRIVE_CLIENT_SECRET=${GOOGLE_DRIVE_CLIENT_SECRET} \
    GOOGLE_DRIVE_REDIRECT_URI=${GOOGLE_DRIVE_REDIRECT_URI} \
    GOOGLE_DRIVE_REFRESH_TOKEN=${GOOGLE_DRIVE_REFRESH_TOKEN}

RUN npm run build

FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production PORT=3000
COPY --from=builder /app .
RUN groupadd -r nodejs && useradd -r -g nodejs nextjs
USER nextjs
EXPOSE 3000
CMD ["npm", "run", "start"]
