-- Create ai_voices table for custom voice management
CREATE TABLE public.ai_voices (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NULL,
  provider text NULL,
  voice_id text NULL,
  CONSTRAINT ai_voices_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- Add indexes for better performance
CREATE INDEX idx_ai_voices_provider ON public.ai_voices(provider);
CREATE INDEX idx_ai_voices_voice_id ON public.ai_voices(voice_id);

-- Add comments to explain the table structure
COMMENT ON TABLE public.ai_voices IS 'Custom AI voices added by users for different TTS providers';
COMMENT ON COLUMN public.ai_voices.name IS 'Display name for the custom voice';
COMMENT ON COLUMN public.ai_voices.provider IS 'TTS provider (openai, elevenlabs, google-tts, etc.)';
COMMENT ON COLUMN public.ai_voices.voice_id IS 'Provider-specific voice identifier';

-- Enable Row Level Security (RLS)
ALTER TABLE public.ai_voices ENABLE ROW LEVEL SECURITY;

-- Create policy to allow all operations for now (can be restricted later)
CREATE POLICY "Allow all operations on ai_voices" ON public.ai_voices
  FOR ALL USING (true) WITH CHECK (true); 